image:
  file: .gitpod.Dockerfile
ports:
- port: 6080
  onOpen: notify
- port: 10000-20000
  onOpen: ignore
workspaceLocation: "."
tasks:
- command: start-vnc-session.sh
- command: gp ports await 6080 && gp preview $(gp url 6080)
- command: cd ${HOME} && wget -O .bashrc_iCub https://raw.githubusercontent.com/icub-tech-iit/icub-os-files/master/user-environment/bashrc_iCub_superbuild
- command: cd ~ && printf "if [ -f ~/.bashrc_iCub ]; then\n . ~/.bashrc_iCub\nfi" | cat - ~/.bashrc > temp && mv temp ~/.bashrc && source ~/.bashrc && cd -
- command: cd ~ && printf "export OBJ_SUBDIR=build\n" | cat - ~/.bashrc > temp && mv temp ~/.bashrc && source ~/.bashrc && cd -
